### PR TITLE
Dialyzer!

### PR DESCRIPTION
**Pull request by christophermaier**
It looks like it works now, without littering the output with warnings
about struct field accesses!

### CODE REVIEW

**Comment by kevsmith** [comment]
How does one run dialyzer via mix?

**Comment by christophermaier** [comment]
```
mix dialyzer.plt
mix dialyzer
```

**Comment by vanstee** [comment]
:+1:

**Comment by christophermaier** [comment]
Withdrawing for the time being, pending some more configuration investigations.

**Pull request closed without merging**
