### PR TITLE
Replace slack token with fake token in cassettes

### PR DESCRIPTION
**Pull request by vanstee**

### CODE REVIEW

**Comment by christophermaier** [comment]
Do we need to change any tokens we use in tests to be `"xoxb-filtered-token"` now?

**Comment by christophermaier** [comment]
Also, are there any implications for how we re-create / add new cassettes now?

**Comment by vanstee** [comment]
Nope. Exvcr still matches requests correctly even though we're using the real Slack token while making those requests. We're just no longer writing that real token to the recorded cassette. Everything else stays the same.

**Comment by christophermaier** [comment]
@vanstee Sweet... :shipit:

**Pull request merged**
