### PR TITLE
Nest chat_handles under users

### PR DESCRIPTION
**Pull request by jsteiner**
We needed a way for non-admin users to view their own chat handles. We
could have opened up chat_handle#index to the current_user, but I think
this is a more desirable option since it's a bit easier from an
implementation side in Cog, and it prevents having to make a second
request just to get the associated chat handle.

### CODE REVIEW

**Comment by jsteiner** [comment]
Should I delete https://github.com/operable/cog/blob/master/web/controllers/v1/chat_handle_controller.ex#L15-L21 as well? This essentially replaces the need for that, but I wasn't sure if it needs to stick around for any reason.

**Comment by imbriaco** [comment]
@jsteiner I think we can lose the function for listing a user chat handle in the chat handle controller. I don't see why we'd need that for anything else.

**Comment by jsteiner** [comment]
@imbriaco updated

**Comment by imbriaco** [comment]
Note: A Contributor License Agreement was not required for this PR because this work was done under contract.

**Pull request merged**
