### PR TITLE
Add ExCoveralls for test coverage reporting

### PR DESCRIPTION
**Pull request by christophermaier**
Run `make coverage` to run tests, producing a coverage report. An
overview will be printed to the terminal, but open
`cover/excoveralls.html` for a more detailed report.

Does not (yet?) post anything to coveralls.io.

### CODE REVIEW

**Comment by vanstee** [comment]
We might not have the best coverage percentage yet, but it might be nice to have buildkite check the change in coverage and fail if it goes below some threshold.

**Comment by imbriaco** [comment]
I'm :-1: on arbitrarily failing the build right now until we get more experience with these tools.

**Comment by christophermaier** [comment]
Just to clarify, this is not wiring up anything to CI builds right now. Just adding it to be a source of information that devs can use to drive their work for now.

**Comment by mpeck** [comment]
I think it's a great idea to get some of these tools integrated into our dev process. It's probably time that we start thinking more about these things. I'm in agreement with @imbriaco though regarding the ci bits though. :+1:

**Pull request merged**
